name: 'publish'

on:
  push:
    branches:
      - main

jobs:
  publish-tauri:
    permissions:
      contents: write
    runs-on: windows-latest
    environment: release
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install frontend dependencies
        run: pnpm install --frozen-lockfile --strict-peer-dependencies

      - name: Read releaseBody from file
        run: |
          export RELEASE_BODY=$(cat CHANGELOG.txt)
          echo "RELEASE_BODY=$RELEASE_BODY" >> $GITHUB_ENV

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          # RELEASE_BODY: ${{ env.RELEASE_BODY }}
        with:
          tauriScript: pnpm tauri
          tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'OverBuddy v__VERSION__'
          releaseBody: ${{ env.RELEASE_BODY }}
          releaseDraft: true
          prerelease: false
